- hosts: localhost
  tasks:
  - name: "Instaling Required Packages (apt)"
    apt:
      name: "{{ packages }}"
      state: present
    become: true
    vars:
      packages:
      - git
      - docker
      - docker-compose
      - python3-pip
      - i3 
      - tmux
      - fonts-cascadia-code
  - name: "Installing Required Packages (snap)"
    snap: 
      name: "{{ packages }}"
      state: present
      classic: true
    become: true
    vars:
      packages:
      - nvim
      - alacritty
  - name: "Configure Github User Email"
    git_config:
      name: user.email
      scope: global
      value: 'wesley.ford@gatech.edu'
   
  - name: "Configure Github User Name"
    git_config:
      name: user.name
      scope: global
      value: "Wesley Ford"

  - name: "Configure Github Editor"
    git_config:
      name: core.editor
      scope: global
      value: nvim

  - name: "Create bare dotfiles git repo"
    git:
      repo: git@github.com:waford/.dotfiles.git
      dest: ~/.dotfiles
      bare: true
  - name: "Checkout dotfiles"
    shell:
      cmd: '/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout -f'

  - block:
    - name: "Mapping CAPS->CTL"
      lineinfile:
        path: /etc/default/keyboard
        line: 'XKBOPTIONS="ctrl:nocaps"'
        regexp: 'XKBOPTIONS'
        state: present

    - name: "Update Keyboard Mapping"
      command: dpkg-reconfigure -f noninteractive keyboard-configuration

    become: yes
    become_user: root
