[font]
size=6

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "BoldItalic"


[shell]
program = "tmux"

[window]
opacity = 0.1
